spring:
  datasource:
    url: jdbc:mysql://localhost:3306/statistics?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create-drop
    database: mysql
    show-sql: true
  data:
    jpa:
      repositories:
        enabled: true
pages:
    all: 3