spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/statistics?allowPublicKeyRetrieval=true&
#                                                useUnicode=true&
#                                                useJDBCCompliantTimezoneShift=true&
#                                                useLegacyDatetimeCode=false&
#                                                serverTimezone=UTC&
#                                                characterEncoding=UTF-8&
#                                                useSSL=false
    url: ${DATABASE_URL}
#    username: root
    username: ${USERNAME}
#    password: root
    password: ${PASSWORD}
  jpa:
    hibernate.ddl-auto: create
    database: postgresql
    show-sql: false
  data:
    jpa:
      repositories:
        enabled: true
server:
  port: ${PORT:8080}