spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
#    url: jdbc:mysql://localhost:3306/statistics?allowPublicKeyRetrieval=true&
#                                                useUnicode=true&
#                                                useJDBCCompliantTimezoneShift=true&
#                                                useLegacyDatetimeCode=false&
#                                                serverTimezone=UTC&
#                                                characterEncoding=UTF-8&
#                                                useSSL=false
    username: root
    username: ${JDBC_DATABASE_USERNAME}
    password: root
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    database: mysql
    show-sql: true
  data:
    jpa:
      repositories:
        enabled: true
